import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import vm from 'node:vm'
test('coordinate helper contract is present',()=>{const source=readFileSync('src/client/index.tsx','utf8');assert.match(source,/normalizeCoordinate/);assert.match(source,/Math\.min\(1, Math\.max\(0/)})
test('client uses the native tool view and right sidebar surface',()=>{const source=readFileSync('src/client/index.tsx','utf8');assert.match(source,/tool\.call\.toolview/);assert.match(source,/tool\.details\.toolview/);assert.match(source,/function DetailsPanel/);assert.match(source,/function openIfIdle/);assert.match(source,/harmony_preview_start/);assert.match(source,/props\?\.block/);assert.match(source,/data-state=\{state\}/);assert.match(source,/position:absolute;top:0;right:0;bottom:0/);assert.match(source,/Recents/);assert.match(source,/Rotate view/);assert.match(source,/visibilityState/)})
test('bundle registers the actual ModuleLoader wrapper',()=>{let registered;const sandbox={window:{__ModuleLoader__:{load:value=>{registered=value}}}};vm.createContext(sandbox);vm.runInContext(readFileSync('lib/client.js','utf8'),sandbox);assert.equal(registered.id,'dsh-harmonyos-plugin');assert.equal(typeof registered.factory,'function')})
test('tool result parser handles DSH text content arrays',async()=>{const {toolResultSessionId}=await import('../lib/client/index.mjs?result-test='+Date.now());assert.equal(toolResultSessionId({content:[{type:'text',text:'{"sessionId":"session-1"}'}]}),'session-1');assert.equal(toolResultSessionId({result:{sessionId:'session-2'}}),'session-2');assert.equal(toolResultSessionId({output:'{"deviceId":"device-1"}'}),undefined)})
test('compiled client registers keyed tool and details slots',async()=>{const previous=globalThis.document;globalThis.document={getElementById:()=>null,createElement:()=>({}),head:{append(){}}};try{const {apply}=await import('../lib/client/index.mjs?slot-test='+Date.now());const records=[];const ctx={slots:{inject:(name,factory)=>records.push({name,definition:factory()}),register:definition=>definition}};apply(ctx);assert.equal(records.filter(item=>item.name==='tool.call.toolview').length,7);assert.equal(records.filter(item=>item.name==='tool.details.toolview').length,7);assert.ok(records.some(item=>item.definition.key==='harmony_preview_start'))}finally{if(previous===undefined)delete globalThis.document;else globalThis.document=previous}})
