import React, { useEffect, useRef, useState } from 'react'
export type Coordinate = { x: number; y: number }
export function normalizeCoordinate(point: Coordinate, width: number, height: number): Coordinate {
  if (!Number.isFinite(width) || !Number.isFinite(height) || width <= 0 || height <= 0) throw new Error('画面尺寸无效')
  return { x: Math.min(1, Math.max(0, point.x / width)), y: Math.min(1, Math.max(0, point.y / height)) }
}
const API = '/_dsh/dsh-harmonyos'
type Session = { sessionId: string; deviceId: string; connected: boolean; state: string; frameId?: string; width?: number; height?: number; error?: string }
type Controller = { session?: Session; token?: string; expiresAt?: number; open: () => void; close: () => void; stop: () => Promise<void>; refresh: () => Promise<void> }
const controllers = new Map<string, Controller>(); let active: Controller | undefined
async function request<T>(path: string, init?: RequestInit): Promise<T> { const res = await fetch(API + path, init); if (!res.ok) throw new Error((await res.text()).slice(0, 300) || res.statusText); return await res.json() as T }
async function grant(sessionId: string) { return request<{token:string;expiresAt:number}>('/grant', { method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify({ sessionId }) }) }
async function frame(s: Session, token: string) { const r=await fetch(API+'/frame?sessionId='+encodeURIComponent(s.sessionId)+'&token='+encodeURIComponent(token)); if(!r.ok) throw new Error('读取画面失败'); const blob=await r.blob(); return { url:URL.createObjectURL(blob), id:r.headers.get('X-Frame-Id')||undefined, width:Number(r.headers.get('X-Frame-Width'))||undefined, height:Number(r.headers.get('X-Frame-Height'))||undefined } }
function jsonValue(block:any):any { const v=block?.result??block?.output??block?.value??block?.content; const t=Array.isArray(v)?v.find((x:any)=>x?.type==='text')?.text:v; if(typeof t==='string')try{return JSON.parse(t)}catch{return t} return t }
function controllerFor(sessionId?:string): Controller { if(sessionId && controllers.has(sessionId)) return controllers.get(sessionId)!; const c:Controller={ open(){active=c;(c as any).visible=true}, close(){(c as any).visible=false}, async stop(){if(!c.session||!c.token)return;c.session=await request<Session>('/stop',{method:'POST',headers:{authorization:'Bearer '+c.token,'content-type':'application/json'},body:JSON.stringify({sessionId:c.session.sessionId})})}, async refresh(){if(!c.session)return;if(!c.token||(c.expiresAt??0)-Date.now()<10000){const g=await grant(c.session.sessionId);c.token=g.token;c.expiresAt=g.expiresAt}c.session=await request<Session>('/status?sessionId='+encodeURIComponent(c.session.sessionId),{headers:{authorization:'Bearer '+c.token}})}}; if(sessionId)controllers.set(sessionId,c); return c }
function usePolling(c:Controller){const[,setTick]=useState(0);useEffect(()=>{if(!c.session)return;let gone=false;const poll=async()=>{try{await c.refresh();if(!c.session||!c.token)return;const f=await frame(c.session,c.token);await new Promise<void>((ok,no)=>{const img=new Image();img.onload=()=>ok();img.onerror=()=>no(new Error('画面加载失败'));img.src=f.url});(c as any).frameUrl=f.url;c.session={...c.session,frameId:f.id,width:f.width,height:f.height,connected:true,state:'connected'};setTick(x=>x+1)}catch(e){if(!gone&&c.session){c.session={...c.session,connected:false,state:'error',error:String(e)};setTick(x=>x+1)}}};void poll();const id=window.setInterval(()=>{if(!gone)void poll()},1000);return()=>{gone=true;window.clearInterval(id)}},[c, c.session?.sessionId])}
function Panel({c}:{c:Controller}){const[,tick]=useState(0);const[devices,setDevices]=useState<{serial:string;state:string}[]>([]);const[selected,setSelected]=useState('');const[text,setText]=useState('');const[busy,setBusy]=useState(false);usePolling(c);const s=c.session;useEffect(()=>{if(!s)void request<{devices:{serial:string;state:string}[]}>('/devices').then(x=>{setDevices(x.devices);if(x.devices.length===1)setSelected(x.devices[0].serial)}).catch(()=>undefined)},[s]);if(!s)return <div className="dsh-hm-panel"><header><b>鸿蒙设备预览</b><button onClick={c.close} aria-label="关闭">×</button></header><label>选择设备<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">请选择设备</option>{devices.map(d=><option key={d.serial} value={d.serial}>{d.serial} · {d.state}</option>)}</select></label><button disabled={!selected||busy} onClick={async()=>{setBusy(true);try{const started=await request<Session>('/start',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({deviceId:selected})});c.session=started;controllers.set(started.sessionId,c);active=c;tick(x=>x+1)}finally{setBusy(false)}}}>开始预览</button></div>;const disabled=!s.connected||s.state==='error';const send=async(body:any)=>{if(disabled||!c.token)return;c.session=await request<Session>('/control',{method:'POST',headers:{authorization:'Bearer '+c.token,'content-type':'application/json'},body:JSON.stringify({sessionId:s.sessionId,frameId:s.frameId,...body,meta:{plugin:'dsh-harmonyos',sessionId:s.sessionId,deviceId:s.deviceId,frameId:s.frameId,width:s.width,height:s.height,state:s.state}})});tick(x=>x+1)};return <div className="dsh-hm-panel"><header><div><b>鸿蒙设备预览</b><span className={s.connected?'ok':'bad'}>{s.connected?'已连接':'已断开'}</span></div><button onClick={c.close} aria-label="关闭">×</button></header><div className="dsh-hm-screen">{(c as any).frameUrl?<img src={(c as any).frameUrl} alt="鸿蒙设备屏幕"/>:<span>正在获取画面…</span>}</div><div className="dsh-hm-meta">{s.deviceId} · {s.width??'—'}×{s.height??'—'} · frame {s.frameId??'—'}</div><div className="dsh-hm-controls"><button disabled={disabled} onClick={()=>void send({action:'button',key:'back'})}>返回</button><button disabled={disabled} onClick={()=>void send({action:'button',key:'home'})}>主页</button><button disabled={disabled} onClick={()=>void send({action:'button',key:'power'})}>电源</button><button disabled={disabled} onClick={()=>void send({action:'tap',x:.5,y:.5})}>点击中心</button><button disabled={disabled} onClick={()=>void send({action:'long_press',x:.5,y:.5})}>长按中心</button></div><form onSubmit={e=>{e.preventDefault();if(text)void send({action:'type',text}).then(()=>setText(''))}}><input aria-label="输入文本" disabled={disabled} value={text} onChange={e=>setText(e.target.value)} placeholder="输入到设备"/><button disabled={disabled||!text}>发送</button></form><footer><button className="danger" onClick={()=>void c.stop()}>停止会话</button></footer></div>}
function ToolView(props:any){const c=controllerFor();const data=jsonValue(props.block);useEffect(()=>{if(props.toolName==='harmony_preview_start'&&data?.sessionId&&!active){c.session=data;controllers.set(data.sessionId,c);active=c;open(c)}},[props.toolName,data?.sessionId]);if(props.toolName==='harmony_preview_start'&&data?.sessionId)return <button className="dsh-hm-card" onClick={()=>open(c)}>鸿蒙预览已启动 · {data.deviceId??''}<span>打开预览</span></button>;return <div className="dsh-hm-card">鸿蒙工具：{props.toolName}</div>}
function Portal({c}:{c:Controller}){const[visible,setVisible]=useState(Boolean((c as any).visible));useEffect(()=>{c.open=()=>{active=c;(c as any).visible=true;setVisible(true)};c.close=()=>{(c as any).visible=false;setVisible(false)}},[c]);return visible?<Panel c={c}/>:null}
function open(c:Controller){if(!(c as any).dispose){const root=document.createElement('div');root.id='dsh-harmonyos-portal';document.body.append(root);const rd=require('react-dom/client').createRoot(root);rd.render(<Portal c={c}/>);(c as any).dispose=()=>{rd.unmount();root.remove()}}c.open()}
function Dock(props:any){const c=controllerFor(props.sessionId);if(!c.session&&!active)return null;return <button className="dsh-hm-dock" onClick={()=>open(c)} aria-label="打开鸿蒙预览">鸿蒙预览{c.session?.connected?' · 已连接':''}</button>}
const CSS =   '#dsh-harmonyos-portal{position:fixed;inset:0;z-index:2147483000;pointer-events:none}.dsh-hm-panel{pointer-events:auto;position:absolute;top:16px;right:16px;width:min(420px,calc(100vw - 32px));max-height:calc(100vh - 32px);overflow:auto;padding:16px;border:1px solid var(--dsw-alias-border-l1,#d9dce3);border-radius:16px;background:var(--dsw-alias-bg-elevated,#fff);color:var(--dsw-alias-label-primary,#16181d);box-shadow:0 18px 60px #0003;font:13px system-ui,sans-serif}.dsh-hm-panel header,.dsh-hm-panel form,.dsh-hm-controls,.dsh-hm-panel footer{display:flex;align-items:center;gap:8px}.dsh-hm-panel header{justify-content:space-between;margin-bottom:12px}.dsh-hm-panel header button{margin-left:auto}.dsh-hm-panel button,.dsh-hm-panel select,.dsh-hm-panel input{min-height:32px;border:1px solid var(--dsw-alias-border-l1,#d9dce3);border-radius:8px;background:var(--dsw-alias-bg-base,#fff);color:inherit;padding:6px 10px}.dsh-hm-panel button{cursor:pointer}.dsh-hm-panel button:disabled{cursor:not-allowed;opacity:.5}.dsh-hm-panel label{display:grid;gap:6px;margin-bottom:10px}.dsh-hm-panel select,.dsh-hm-panel input{width:100%;box-sizing:border-box}.dsh-hm-screen{display:grid;place-items:center;min-height:220px;margin:12px 0;overflow:hidden;border-radius:10px;background:#111;color:#aaa}.dsh-hm-screen img{display:block;max-width:100%;max-height:52vh;object-fit:contain}.dsh-hm-meta{margin:8px 0;color:var(--dsw-alias-label-secondary,#6b7280);font-size:11px}.dsh-hm-controls{flex-wrap:wrap}.dsh-hm-panel form{margin-top:10px}.dsh-hm-panel form input{flex:1}.dsh-hm-panel footer{justify-content:flex-end;margin-top:12px}.dsh-hm-panel .danger{color:#b42318}.dsh-hm-panel .ok{color:#16803c;margin-left:8px}.dsh-hm-panel .bad{color:#b42318;margin-left:8px}.dsh-hm-card,.dsh-hm-dock{display:flex;gap:8px;align-items:center}.dsh-hm-card{width:100%;padding:8px;border:1px solid var(--dsw-alias-border-l1,#d9dce3);border-radius:8px;background:transparent;color:inherit;cursor:pointer}.dsh-hm-card span{margin-left:auto;color:var(--dsw-alias-label-secondary,#6b7280)}.dsh-hm-dock{border:0;background:transparent;color:inherit;cursor:pointer}'
function installStyles(){if(document.getElementById('dsh-harmonyos-styles'))return;const style=document.createElement('style');style.id='dsh-harmonyos-styles';style.textContent=CSS;document.head.append(style)}
export const inject=['slots']
export function apply(ctx:any){installStyles();const names=['harmony_devices','harmony_preview_start','harmony_preview_stop','harmony_preview_info','harmony_screenshot','harmony_interact'];for(const key of names)ctx.slots.inject('tool.call.toolview',()=>ctx.slots.register({name:'tool.call.toolview',key},ToolView));ctx.slots.inject('conversation.input.dock',()=>ctx.slots.register({name:'conversation.input.dock',id:'dsh-harmonyos',order:80,label:'鸿蒙预览'},Dock))}
